<a href="https://colab.research.google.com/github/Ryan20-h/data-science-toolkit/blob/main/Tutorial_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [7]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/Suicide_Detection.csv/Suicide_Detection.csv')
display(df.head())

   Unnamed: 0                                               text        class
0           2  Ex Wife Threatening SuicideRecently I left my ...      suicide
1           3  Am I weird I don't get affected by compliments...  non-suicide
2           4  Finally 2020 is almost over... So I can never ...  non-suicide
3           8          i need helpjust help me im crying so hard      suicide
4           9  I’m so lostHello, my name is Adam (16) and I’v...      suicide

2. Evaluate if the data is good or not. Does it have enough samples?

The data is good and have enough samples

In [8]:
print("Rows and columns:",df.shape)
print("Number of data:",df.size)
print("Repeated unnamed:",df["Unnamed: 0"].duplicated().sum())
print("Suicided (0=No,1=Yes):")
print(df["class"].value_counts())

Rows and columns: (232074, 3)
Number of data: 696222
Repeated unnamed: 0
Suicided (0=No,1=Yes):
class
suicide        116037
non-suicide    116037
Name: count, dtype: int64

3. How many features does it have? Is it enough?

Answer:there are only 3 columns(one outcome : class and other 2 columns) It is not enough for study

In [9]:
print("All columns:")
print(df.columns.tolist())
print("Number of columns:",len(df.columns))
print("Possible input columns:",len(df.columns)-1)

All columns:
['Unnamed: 0', 'text', 'class']
Number of columns: 3
Possible input columns: 2

4. How many samples/observation does it have? Is it enough?

Answer: there are 232074 of samples for study and it is more than enough

In [10]:
print("Number of samples:",len(df))

Number of samples: 232074

5. What are the datatypes does the dataset consist of?

In [11]:
print(df.dtypes)

Unnamed: 0     int64
text          object
class         object
dtype: object

6. How many columns have null values? If yes, which column, which rows

8. Does it have missing values? If yes, which column, which row.

Answer: no mising values in each column and rows.

In [12]:
missing= df.isnull().sum()
print ("Missing values in each column:")
print(missing)
print("\nColumns with any missing values:")
print(missing[missing>0])
print("\nNumber of columns with missing values:",(missing > 0).sum())

Missing values in each column
Unnamed: 0    0
text          0
class         0
dtype: int64

Columns with any missing values:
Series([], dtype: int64)

Number of columns with missing values: 0

In [15]:
#axis=1 means you are checking the rows horizontally one by one
#axis=0 means going down the columns
rows_missing = df[df.isnull().any(axis=1)]
print("Number of rows with at least one missing value:",len(rows_missing))
print("First 10 rows containing missing values:")
display(rows_missing.head(10))

# To find EXACT position for one particular column
column_to_check="text"
print("Patient with missing ",column_to_check,":")
print(df.loc[df[column_to_check].isnull(),"Unnamed: 0"].tolist())

Number of rows with at least one missing value: 0
First 10 rows containing missing values:

Empty DataFrame
Columns: [Unnamed: 0, text, class]
Index: []

Patient with missing  text :
[]

7. Which column is the feature, which is the target output?

Answer:The target is class. The feature is only the text that they write. The unnamed: 0 is excluded from the features beacuse it identifies the patient rather than decsribing them.No prediction model is trained in this excercise.

In [16]:
target = "class"
features = df.drop(columns=["class","Unnamed: 0"])

print("Target column:",target)
print("Features columns:",features.columns.tolist())
print("Target value:",df[target].unique())

Target column: class
Features columns: ['text']
Target value: ['suicide' 'non-suicide']

9. What kind of question can be asked, should we ask. Does the dataset suits the question we are asking

Question: what is the rate of suicide?

This question is suitable because the 'class' column recorded the patient who suicide and who didn't.

In [25]:
suicide_rate=(df["class"]=="suicide").mean()*100
print("The rate of suicide:",suicide_rate,"%")

The rate of suicide: 50.0 %